"""Initialize the `.agents/` directory structure in a program's specs repo.

Per spec.md: `otaman onboard program-init` SHALL initialize `.agents/` structure.

Structure created:
    .agents/
        queue/
            <no files>
        blocked/
            <no files>
        reviews/
            pending/
            done/
        knowledge/
            <no files>
        ownership.json
        agents.yaml
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

_AGENTS_YAML_TEMPLATE = """\
# agents.yaml — generated by `otaman onboard program-init`
# List the agents active in this program.
# Each entry: name, type, repo, owner_email (optional)
#
# Example:
#   - name: cli-agent
#     type: claude
#     repo: {program}-cli
#
agents: []
"""

_OWNERSHIP_TEMPLATE: dict[str, Any] = {
    "__comment": "Generated by otaman onboard program-init. Maps repo names to agent owners.",
    "version": 1,
    "repos": {},
}

_GITKEEP = ""  # empty .gitkeep to preserve empty dirs in git


def init_agents_structure(specs_path: Path, program_name: str) -> list[str]:
    """Create the `.agents/` directory structure under *specs_path*.

    Returns a list of created paths (relative to specs_path) for logging.
    Idempotent — does not overwrite existing files.
    """
    agents_dir = specs_path / ".agents"
    created: list[str] = []

    subdirs = [
        agents_dir / "queue",
        agents_dir / "blocked",
        agents_dir / "reviews" / "pending",
        agents_dir / "reviews" / "done",
        agents_dir / "knowledge",
    ]
    for subdir in subdirs:
        if not subdir.exists():
            subdir.mkdir(parents=True, exist_ok=True)
            gitkeep = subdir / ".gitkeep"
            gitkeep.write_text(_GITKEEP)
            created.append(str(gitkeep.relative_to(specs_path)))

    # ownership.json
    ownership_path = agents_dir / "ownership.json"
    if not ownership_path.exists():
        payload = dict(_OWNERSHIP_TEMPLATE)
        payload["program"] = program_name
        ownership_path.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
        created.append(str(ownership_path.relative_to(specs_path)))

    # agents.yaml
    agents_yaml_path = agents_dir / "agents.yaml"
    if not agents_yaml_path.exists():
        agents_yaml_path.write_text(
            _AGENTS_YAML_TEMPLATE.format(program=program_name), encoding="utf-8"
        )
        created.append(str(agents_yaml_path.relative_to(specs_path)))

    return created
