"""Git initialization helpers for `otaman onboard program-init`.

Per spec.md: after generating platform.yaml and initializing `.agents/`,
the CLI SHALL commit the initial state to the program's `-specs` repo with
a descriptive commit message (audit trail requirement).

This module is intentionally thin: it shells out to `git` via subprocess
and tolerates failures gracefully (the init flow must not fail because git
is unavailable or the repo was already initialized by the user).
"""

from __future__ import annotations

import subprocess
from pathlib import Path
from typing import Any


def _run_git(args: list[str], cwd: Path) -> tuple[int, str, str]:
    """Run `git <args>` in *cwd*; return (returncode, stdout, stderr)."""
    try:
        result = subprocess.run(
            ["git", *args],
            cwd=cwd,
            capture_output=True,
            text=True,
            timeout=30,
        )
        return result.returncode, result.stdout.strip(), result.stderr.strip()
    except FileNotFoundError:
        return -1, "", "git not found on PATH"
    except subprocess.TimeoutExpired:
        return -1, "", "git command timed out"
    except Exception as exc:
        return -1, "", str(exc)


def ensure_git_repo(specs_path: Path) -> str | None:
    """Ensure *specs_path* is a git repo (run `git init` if not).

    Returns None on success, an error message string on failure.
    """
    git_dir = specs_path / ".git"
    if git_dir.is_dir():
        return None  # already a repo

    rc, _, err = _run_git(["init", "-b", "main", str(specs_path)], cwd=specs_path.parent)
    if rc != 0:
        # Older git (<2.28) may not support -b; retry without it
        rc2, _, err2 = _run_git(["init", str(specs_path)], cwd=specs_path.parent)
        if rc2 != 0:
            return f"git init failed: {err2 or err}"
    return None


def create_gitignore(specs_path: Path) -> None:
    """Write a minimal .gitignore if one doesn't exist."""
    gitignore = specs_path / ".gitignore"
    if gitignore.exists():
        return
    gitignore.write_text(
        "# Generated by otaman onboard program-init\n"
        ".init-state.yaml\n"
        "__pycache__/\n"
        "*.pyc\n"
        ".DS_Store\n",
        encoding="utf-8",
    )


def initial_commit(specs_path: Path, program_name: str, answers: dict[str, Any]) -> str | None:
    """Stage all files in *specs_path* and create the initial commit.

    Returns None on success, an error message string on failure.
    This call is idempotent — if commits already exist it does nothing.
    """
    # Check if HEAD already points to a commit (repo already has history)
    rc, stdout, _ = _run_git(["rev-parse", "--verify", "HEAD"], cwd=specs_path)
    if rc == 0 and stdout:
        # Already has commits — do not create another initial commit
        return None

    # Stage everything
    rc, _, err = _run_git(["add", "."], cwd=specs_path)
    if rc != 0:
        return f"git add failed: {err}"

    processes = answers.get("processes") or []
    if answers.get("strategy_opt_in"):
        processes = list(processes) + ["strategy"]
    edition = answers.get("active_edition", "ce").upper()
    mode = answers.get("mode", 1)
    roles = answers.get("roles") or []

    commit_msg = (
        f"chore(init): otaman program-init — {program_name}\n\n"
        f"Edition: {edition}  Mode: {mode}\n"
        f"Processes: {', '.join(sorted(processes)) or 'none'}\n"
        f"Roles: {', '.join(sorted(roles)) or 'none'}\n\n"
        "Generated by `otaman onboard program-init`.\n"
    )

    # Set a committer identity if none is configured (CI / fresh environments)
    env: dict[str, str] = {}
    rc_user, user_out, _ = _run_git(["config", "user.email"], cwd=specs_path)
    if rc_user != 0 or not user_out:
        env["GIT_AUTHOR_NAME"] = "otaman-cli"
        env["GIT_AUTHOR_EMAIL"] = "otaman-cli@localhost"
        env["GIT_COMMITTER_NAME"] = "otaman-cli"
        env["GIT_COMMITTER_EMAIL"] = "otaman-cli@localhost"

    try:
        import os

        merged_env = {**os.environ, **env}
        result = subprocess.run(
            ["git", "commit", "-m", commit_msg],
            cwd=specs_path,
            capture_output=True,
            text=True,
            timeout=30,
            env=merged_env,
        )
        if result.returncode != 0:
            return f"git commit failed: {result.stderr.strip()}"
    except Exception as exc:
        return f"git commit error: {exc}"

    return None
